### PR TITLE
Feat: Add Encryption to Certificate and PDFStorage S3 bucket

### PR DESCRIPTION
**Pull request by petter-a**
Does what it say. Enables encryption and best practise access control to the s3 buckets

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-mzaapw Certifkat S3-bucket saknar kryptering](https://app.clickup.com/t/mzaapw)

**Review by karlknowit — APPROVED** [review]
Looks good!

**Review by dannil76 — COMMENTED** [review]
Assume you have tested so that the affected services - PDF and certs still working?

**Comment by petter-a** [comment]
> Assume you have tested so that the affected services - PDF and certs still working?

@dannil76 Yes, however the change in https://github.com/helsingborg-stad/helsingborg-io-sls-api/pull/297 needs to go first

**Review by dannil76 — APPROVED** [review]
In trust with @karlknowit

**Pull request merged**
