### PR TITLE
Fix/cleanup

### PR DESCRIPTION
**Pull request by jonatanhanson**
- Renamed services for better consistency
- Added Eslint
- Added Husky
- Fixed lint warnings

### CODE REVIEW

**Comment by TeddyAndersson** [comment]
Are there any steps for how i can update my current AWS environment and test so that these changes works as expected? 😅 

I know that you had some issues with conflicting exports etc @jonatanhanson :D

**Comment by TeddyAndersson** [comment]
The cleanup otherwise looks good, just want to test the deployment before i give a thumbs up 👍

**Comment by dannil76** [comment]
> The cleanup otherwise looks good, just want to test the deployment before i give a thumbs up 👍

One option is to deploy to a new stage ie. `$sls deploy --stage somestagename`
In this way you'll have a separate setup at aws

**Comment by jonatanhanson** [comment]
> Are there any steps for how i can update my current AWS environment and test so that these changes works as expected? 😅
> 
> I know that you had some issues with conflicting exports etc @jonatanhanson :D



> > The cleanup otherwise looks good, just want to test the deployment before i give a thumbs up 👍
> 
> One option is to deploy to a new stage ie. `$sls deploy --stage somestagename`
> In this way you'll have a separate setup at aws

Thats probably a better way because it's pretty painful to wipe your existing environment just to test this branch :P

**Review by dannil76 — CHANGES_REQUESTED** [review]

**Review by TeddyAndersson — APPROVED** [review]
Have no further comments on these changes, struggle to redeploy everything due to name changes. But it works as expected a big thumbs up from me. Great work! 👍

**Review by dannil76 — APPROVED** [review]

**Pull request merged**
